  CREATE TABLE "ONIGAWARA"."ITEM" 
   (	"IDX" NUMBER(3,0), 
	"NAME" VARCHAR2(100 BYTE), 
	"ATK" NUMBER(3,0), 
	"DEF" NUMBER(3,0), 
	"STR" NUMBER(3,0), 
	"DEX" NUMBER(3,0), 
	"INT" NUMBER(3,0), 
	"C_ABLE" NUMBER(1,0), 
	"EFFECT" VARCHAR2(100 BYTE), 
	"SUB" LONG, 
	"PRICE" NUMBER(5,0), 
	"CLASS" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into ONIGAWARA.ITEM
SET DEFINE OFF;
