  CREATE TABLE "ONIGAWARA"."NPC" 
   (	"IDX" NUMBER(3,0), 
	"NAME" VARCHAR2(100 BYTE), 
	"SUB" LONG
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into ONIGAWARA.NPC
SET DEFINE OFF;
