  CREATE TABLE "ONIGAWARA"."SKILL" 
   (	"IDX" NUMBER(3,0), 
	"NAME" VARCHAR2(100 BYTE), 
	"AR" NUMBER(3,0), 
	"HP" NUMBER(3,0), 
	"MP" NUMBER(3,0), 
	"CLASS" VARCHAR2(100 BYTE), 
	"CALC" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into ONIGAWARA.SKILL
SET DEFINE OFF;
