CREATE TABLE "ONIGAWARA"."BOARD" 
   (	"IDX" NUMBER(10,0), 
	"USER_ID" VARCHAR2(100 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENTS" LONG, 
	"HIT" NUMBER(10,0), 
	"NDATE" DATE
   )
   
  CREATE TABLE "ONIGAWARA"."CHARACTER" 
   (	"USER_ID" VARCHAR2(100 BYTE), 
	"CHAR_NAME" VARCHAR2(100 BYTE), 
	"CHAR_LV" NUMBER(4,0), 
	"CHAR_STR" NUMBER(4,0), 
	"CHAR_DEX" NUMBER(4,0), 
	"CHAR_HP" NUMBER(4,0), 
	"CHAR_ATK" NUMBER(4,0), 
	"CHAR_DEF" NUMBER(4,0), 
	"CHAR_AGI" NUMBER(4,0), 
	"CHAR_CRT" NUMBER(4,0), 
	"CHAR_EXP" NUMBER(4,0)
   )

  CREATE TABLE "ONIGAWARA"."DEV" 
   (	"DEV_ID" VARCHAR2(100 BYTE), 
	"DEV_PW" VARCHAR2(100 BYTE), 
	"DEV_EMAIL" VARCHAR2(20 BYTE)
   )
   
  CREATE TABLE "ONIGAWARA"."EQUIP" 
   (	"WEAPON_NAME" VARCHAR2(100 BYTE), 
	"WEAPON_CODE" NUMBER(4,0), 
	"AMOR_NAME" VARCHAR2(100 BYTE), 
	"AMOR_CODE" NUMBER(4,0), 
	"GLOVES_NAME" VARCHAR2(100 BYTE), 
	"GLOVES_CODE" NUMBER(4,0), 
	"BOOTS_NAME" VARCHAR2(100 BYTE), 
	"BOOTS_CODE" NUMBER(4,0), 
	"SUB1_NAME" VARCHAR2(100 BYTE), 
	"SUB1_CODE" NUMBER(4,0), 
	"SUB2_NAME" VARCHAR2(100 BYTE), 
	"SUB2_CODE" NUMBER(4,0), 
	"SUB3_NAME" VARCHAR2(100 BYTE), 
	"SUB3_CODE" NUMBER(4,0), 
	"SK1_NAME" VARCHAR2(100 BYTE), 
	"SK1_CODE" NUMBER(4,0), 
	"SK2_NAME" VARCHAR2(100 BYTE), 
	"SK2_CODE" NUMBER(4,0),
	"CHAR_NAME" VARCHAR2(100 BYTE)
   )
   
  CREATE TABLE "ONIGAWARA"."INVENTORY" 
   (	"CHAR_NAME" VARCHAR2(100 BYTE), 
	"ITEM_CODE" NUMBER(4,0)
   )
   
  CREATE TABLE "ONIGAWARA"."ITEM" 
   (	"ITEM_CODE" NUMBER(4,0), 
	"ITEM_NAME" VARCHAR2(100 BYTE), 
	"ITEM_ATK" NUMBER(4,0), 
	"ITEM_DEF" NUMBER(4,0), 
	"ITEM_SUB" VARCHAR2(1000 BYTE), 
	"ITEM_PROP" NUMBER(2,0), 
	"ITEM_PRICE" NUMBER(4,0)
   )
   
  CREATE TABLE "ONIGAWARA"."MEMBER" 
   (	"USER_ID" VARCHAR2(100 BYTE), 
	"USER_PW" VARCHAR2(100 BYTE), 
	"NDATE" DATE, 
	"USER_EMAIL" VARCHAR2(100 BYTE)
   )
   
  CREATE TABLE "ONIGAWARA"."MOB" 
   (	"MOB_CODE" NUMBER(4,0), 
	"MOB_NAME" VARCHAR2(100 BYTE), 
	"MOB_LV" NUMBER(4,0), 
	"MOB_STR" NUMBER(4,0), 
	"MOB_DEX" NUMBER(4,0), 
	"MOB_PROP" NUMBER(2,0), 
	"MOB_SK1" NUMBER(4,0), 
	"MOB_SK2" NUMBER(4,0), 
	"MOB_SK3" NUMBER(4,0), 
	"MOB_SK4" NUMBER(4,0), 
	"MOB_SK5" NUMBER(4,0), 
	"MOB_SUB" VARCHAR2(1000 BYTE), 
	"MOB_ATK" NUMBER(4,0), 
	"MOB_DEF" NUMBER(4,0), 
	"MOB_HP" NUMBER
   )
   
  CREATE TABLE "ONIGAWARA"."SKILL" 
   (	"SK_CODE" NUMBER(4,0), 
	"SK_NAME" VARCHAR2(100 BYTE), 
	"SK_ATK" NUMBER(4,0), 
	"SK_DEF" NUMBER(4,0), 
	"SK_SUB" VARCHAR2(1000 BYTE)
   )
   
Insert into ONIGAWARA.CHARACTER (USER_ID,CHAR_NAME,CHAR_LV,CHAR_STR,CHAR_DEX,CHAR_HP,CHAR_ATK,CHAR_DEF,CHAR_AGI,CHAR_CRT,CHAR_EXP) values ('qwe','1111',1,10,10,100,10,0,1,1,0);
Insert into ONIGAWARA.CHARACTER (USER_ID,CHAR_NAME,CHAR_LV,CHAR_STR,CHAR_DEX,CHAR_HP,CHAR_ATK,CHAR_DEF,CHAR_AGI,CHAR_CRT,CHAR_EXP) values ('qwe','aaasdsa',1,10,10,100,10,0,1,1,0);

Insert into ONIGAWARA.DEV (DEV_ID,DEV_PW,DEV_EMAIL) values ('admin','admin',null);

Insert into ONIGAWARA.INVENTORY (CHAR_NAME,ITEM_CODE) values ('1111',2001);
Insert into ONIGAWARA.INVENTORY (CHAR_NAME,ITEM_CODE) values ('1111',2002);
Insert into ONIGAWARA.INVENTORY (CHAR_NAME,ITEM_CODE) values ('1111',3001);
Insert into ONIGAWARA.INVENTORY (CHAR_NAME,ITEM_CODE) values ('1111',3002);
Insert into ONIGAWARA.INVENTORY (CHAR_NAME,ITEM_CODE) values ('1111',4001);
Insert into ONIGAWARA.INVENTORY (CHAR_NAME,ITEM_CODE) values ('1111',4002);
Insert into ONIGAWARA.INVENTORY (CHAR_NAME,ITEM_CODE) values ('1111',5001);
Insert into ONIGAWARA.INVENTORY (CHAR_NAME,ITEM_CODE) values ('1111',5002);
Insert into ONIGAWARA.INVENTORY (CHAR_NAME,ITEM_CODE) values ('1111',1001);
Insert into ONIGAWARA.INVENTORY (CHAR_NAME,ITEM_CODE) values ('1111',1002);

Insert into ONIGAWARA.ITEM (ITEM_CODE,ITEM_NAME,ITEM_ATK,ITEM_DEF,ITEM_SUB,ITEM_PROP,ITEM_PRICE) values (2001,'��������',0,10,'���������̴�',2,10);
Insert into ONIGAWARA.ITEM (ITEM_CODE,ITEM_NAME,ITEM_ATK,ITEM_DEF,ITEM_SUB,ITEM_PROP,ITEM_PRICE) values (4001,'��������',0,5,'����������',4,30);
Insert into ONIGAWARA.ITEM (ITEM_CODE,ITEM_NAME,ITEM_ATK,ITEM_DEF,ITEM_SUB,ITEM_PROP,ITEM_PRICE) values (5002,'����͸�����ź',100,0,'����͸�����ź�̴�',5,100);
Insert into ONIGAWARA.ITEM (ITEM_CODE,ITEM_NAME,ITEM_ATK,ITEM_DEF,ITEM_SUB,ITEM_PROP,ITEM_PRICE) values (2002,'ö����',0,20,'ö�����̴�',2,100);
Insert into ONIGAWARA.ITEM (ITEM_CODE,ITEM_NAME,ITEM_ATK,ITEM_DEF,ITEM_SUB,ITEM_PROP,ITEM_PRICE) values (1001,'�ܰ�',50,0,'�ܰ��̴�',1,0);
Insert into ONIGAWARA.ITEM (ITEM_CODE,ITEM_NAME,ITEM_ATK,ITEM_DEF,ITEM_SUB,ITEM_PROP,ITEM_PRICE) values (3002,'ö�尩',0,20,'ö�尩�̴�',3,200);
Insert into ONIGAWARA.ITEM (ITEM_CODE,ITEM_NAME,ITEM_ATK,ITEM_DEF,ITEM_SUB,ITEM_PROP,ITEM_PRICE) values (1002,'���',100,0,'����̴�',1,100);
Insert into ONIGAWARA.ITEM (ITEM_CODE,ITEM_NAME,ITEM_ATK,ITEM_DEF,ITEM_SUB,ITEM_PROP,ITEM_PRICE) values (3001,'�����尩',0,5,'�����尩�̴�',3,5);
Insert into ONIGAWARA.ITEM (ITEM_CODE,ITEM_NAME,ITEM_ATK,ITEM_DEF,ITEM_SUB,ITEM_PROP,ITEM_PRICE) values (5001,'��ź',10,0,'��ź�̴�',5,100);
Insert into ONIGAWARA.ITEM (ITEM_CODE,ITEM_NAME,ITEM_ATK,ITEM_DEF,ITEM_SUB,ITEM_PROP,ITEM_PRICE) values (4002,'ö����',0,30,'ö�����̴�',4,300);

Insert into ONIGAWARA.MEMBER (USER_ID,USER_PW,NDATE,USER_EMAIL) values ('qwe','qwe',to_date('19/03/25','RR/MM/DD'),'qwe@qwe.qwe');

Insert into ONIGAWARA.MOB (MOB_CODE,MOB_NAME,MOB_LV,MOB_STR,MOB_DEX,MOB_PROP,MOB_SK1,MOB_SK2,MOB_SK3,MOB_SK4,MOB_SK5,MOB_SUB,MOB_ATK,MOB_DEF,MOB_HP) values (1001,'����',10,0,0,3,0,0,0,0,0,'0',0,0,0);
