CREATE TABLE BOARD 
(
  IDX NUMBER(10, 0) NOT NULL 
, USER_ID VARCHAR2(100 BYTE) NOT NULL 
, TITLE VARCHAR2(200 BYTE) NOT NULL 
, CONTENTS LONG NOT NULL 
, HIT NUMBER(10, 0) 
, NDATE DATE 
)
CREATE TABLE CHARACTER 
(
  USER_ID VARCHAR2(100 BYTE) NOT NULL 
, CHAR_NAME VARCHAR2(100 BYTE) NOT NULL 
, CHAR_LV NUMBER(4, 0) 
, CHAR_STR NUMBER(4, 0) 
, CHAR_DEX NUMBER(4, 0) 
, CHAR_HP NUMBER(4, 0) 
, CHAR_ATK NUMBER(4, 0) 
, CHAR_DEF NUMBER(4, 0) 
, CHAR_AGI NUMBER(4, 0) 
, CHAR_CRT NUMBER(4, 0) 
, CHAR_EXP NUMBER(4, 0) 
)
CREATE TABLE DEV 
(
  DEV_ID VARCHAR2(100 BYTE) NOT NULL 
, DEV_PW VARCHAR2(100 BYTE) NOT NULL 
, DEV_EMAIL VARCHAR2(20 BYTE) 
)
CREATE TABLE EQUIP 
(
  AMOR NUMBER(4, 0) 
, GLOVES NUMBER(4, 0) 
, BOOTS NUMBER(4, 0) 
, WEAPON NUMBER(4, 0) 
, SUB1 NUMBER(4, 0) 
, SUB2 NUMBER(4, 0) 
, SUB3 NUMBER(4, 0) 
, SUB4 NUMBER(4, 0) 
, SUB5 NUMBER(4, 0) 
, CHAR_NAME VARCHAR2(100 BYTE) 
)
CREATE TABLE INVENTORY 
(
  CHAR_NAME VARCHAR2(100 BYTE) 
, ITEM_CODE NUMBER(4, 0) 
)
CREATE TABLE ITEM 
(
  ITEM_CODE NUMBER(4, 0) NOT NULL 
, ITEM_NAME VARCHAR2(100 BYTE) NOT NULL 
, ITEM_ATK NUMBER(4, 0) 
, ITEM_DEF NUMBER(4, 0) 
, ITEM_OPT1 NUMBER(4, 0) 
, ITEM_OPT2 NUMBER(4, 0) 
, ITEM_OPT3 NUMBER(4, 0) 
, ITEM_OPT4 NUMBER(4, 0) 
, ITEM_OPT5 NUMBER(4, 0) 
, ITEM_SUB VARCHAR2(1000 BYTE) 
, ITEM_PROP NUMBER(2, 0) 
, ITEM_PRICE NUMBER(4, 0) 
)
CREATE TABLE MEMBER 
(
  USER_ID VARCHAR2(100 BYTE) NOT NULL 
, USER_PW VARCHAR2(100 BYTE) NOT NULL 
, NDATE DATE 
, USER_EMAIL VARCHAR2(100 BYTE) 
)
CREATE TABLE MOB 
(
  MOB_CODE NUMBER(4, 0) NOT NULL 
, MOB_NAME VARCHAR2(100 BYTE) NOT NULL 
, MOB_LV NUMBER(4, 0) 
, MOB_STR NUMBER(4, 0) 
, MOB_DEX NUMBER(4, 0) 
, MOB_PROP NUMBER(2, 0) 
, MOB_OPT1 NUMBER(4, 0) 
, MOB_OPT2 NUMBER(4, 0) 
, MOB_OPT3 NUMBER(4, 0) 
, MOB_OPT4 NUMBER(4, 0) 
, MOB_OPT5 NUMBER(4, 0) 
, MOB_SK1 NUMBER(4, 0) 
, MOB_SK2 NUMBER(4, 0) 
, MOB_SK3 NUMBER(4, 0) 
, MOB_SK4 NUMBER(4, 0) 
, MOB_SK5 NUMBER(4, 0) 
, MOB_SUB VARCHAR2(1000 BYTE) 
, MOB_ATK NUMBER(4, 0) 
, MOB_DEF NUMBER(4, 0) 
)
CREATE TABLE SKILL 
(
  SK_CODE NUMBER(4, 0) 
, SK_NAME VARCHAR2(100 BYTE) 
, SK_ATK NUMBER(4, 0) 
, SK_OPT1 NUMBER(4, 0) 
, SK_OPT2 NUMBER(4, 0) 
, SK_OPT3 NUMBER(4, 0) 
, SK_OPT4 NUMBER(4, 0) 
, SK_OPT5 NUMBER(4, 0) 
, SK_SUB VARCHAR2(1000 BYTE) 
)
Insert into ONIGAWARA.DEV (DEV_ID,DEV_PW,DEV_EMAIL) values ('admin','admin',null);