CREATE TABLE BOARD 
(
  IDX NUMBER(10, 0) 
, USER_ID VARCHAR2(100 BYTE) 
, TITLE VARCHAR2(200 BYTE) 
, CONTENTS LONG 
, HIT NUMBER(10, 0) 
, NDATE DATE 
)
CREATE TABLE CHARACTER 
(
  USER_ID VARCHAR2(100 BYTE) 
, CHAR_NAME VARCHAR2(100 BYTE) 
, CHAR_LV NUMBER(4, 0) 
, CHAR_STR NUMBER(4, 0) 
, CHAR_DEX NUMBER(4, 0) 
, CHAR_HP NUMBER(4, 0) 
, CHAR_ATK NUMBER(4, 0) 
, CHAR_DEF NUMBER(4, 0) 
, CHAR_AGI NUMBER(4, 0) 
, CHAR_CRT NUMBER(4, 0) 
, CHAR_EXP NUMBER(4, 0) 
)
CREATE TABLE DEV 
(
  DEV_ID VARCHAR2(100 BYTE) 
, DEV_PW VARCHAR2(100 BYTE) 
, DEV_EMAIL VARCHAR2(20 BYTE) 
)
CREATE TABLE EQUIP 
(
  WEAPON_CODE NUMBER(4, 0) 
, AMOR_CODE NUMBER(4, 0) 
, GLOVES_CODE NUMBER(4, 0) 
, BOOTS_CODE NUMBER(4, 0) 
, SUB1_CODE NUMBER(4, 0) 
, SUB2_CODE NUMBER(4, 0) 
, SUB3_CODE NUMBER(4, 0) 
, SK1_CODE NUMBER(4, 0) 
, SK2_CODE NUMBER(4, 0) 
, CHAR_NAME VARCHAR2(100 BYTE) 
, USER_ID VARCHAR2(100 BYTE) 
)
CREATE TABLE INVENTORY 
(
  CHAR_NAME VARCHAR2(100 BYTE) 
, ITEM_CODE NUMBER(4, 0) 
)
CREATE TABLE ITEM 
(
  ITEM_CODE NUMBER(4, 0) 
, ITEM_NAME VARCHAR2(100 BYTE) 
, ITEM_ATK NUMBER(4, 0) 
, ITEM_DEF NUMBER(4, 0) 
, ITEM_SUB VARCHAR2(1000 BYTE) 
, ITEM_PROP NUMBER(2, 0) 
, ITEM_PRICE NUMBER(4, 0) 
)
CREATE TABLE MEMBER 
(
  USER_ID VARCHAR2(100 BYTE) 
, USER_PW VARCHAR2(100 BYTE) 
, NDATE DATE 
, USER_EMAIL VARCHAR2(100 BYTE) 
)
CREATE TABLE MOB 
(
  MOB_CODE NUMBER(4, 0) 
, MOB_NAME VARCHAR2(100 BYTE) 
, MOB_LV NUMBER(4, 0) 
, MOB_STR NUMBER(4, 0) 
, MOB_DEX NUMBER(4, 0) 
, MOB_PROP NUMBER(2, 0) 
, MOB_SK1 NUMBER(4, 0) 
, MOB_SK2 NUMBER(4, 0) 
, MOB_SK3 NUMBER(4, 0) 
, MOB_SK4 NUMBER(4, 0) 
, MOB_SK5 NUMBER(4, 0) 
, MOB_SUB VARCHAR2(1000 BYTE) 
, MOB_ATK NUMBER(4, 0) 
, MOB_DEF NUMBER(4, 0) 
, MOB_HP NUMBER 
)
CREATE TABLE SKILL 
(
  SK_CODE NUMBER(4, 0) 
, SK_NAME VARCHAR2(100 BYTE) 
, SK_ATK NUMBER(4, 0) 
, SK_DEF NUMBER(4, 0) 
, SK_SUB VARCHAR2(1000 BYTE) 
)
