-- 내부 생성기를 시도하는 DBMS_METADATA로 ONIGAWARA.CHARACTER 객체에 대한 TABLE DDL을 렌더링할 수 없습니다.
CREATE TABLE CHARACTER 
(
  USER_ID VARCHAR2(100 BYTE) 
, CHAR_NAME VARCHAR2(100 BYTE) 
, CHAR_LV NUMBER(4, 0) 
, CHAR_STR NUMBER(4, 0) 
, CHAR_DEX NUMBER(4, 0) 
, CHAR_HP NUMBER(4, 0) 
, CHAR_ATK NUMBER(4, 0) 
, CHAR_DEF NUMBER(4, 0) 
, CHAR_AGI NUMBER(4, 0) 
, CHAR_CRT NUMBER(4, 0) 
, CHAR_EXP NUMBER(4, 0) 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
