-- 내부 생성기를 시도하는 DBMS_METADATA로 ONIGAWARA.ITEM 객체에 대한 TABLE DDL을 렌더링할 수 없습니다.
CREATE TABLE ITEM 
(
  ITEM_CODE NUMBER(4, 0) 
, ITEM_NAME VARCHAR2(100 BYTE) 
, ITEM_ATK NUMBER(4, 0) 
, ITEM_DEF NUMBER(4, 0) 
, ITEM_SUB VARCHAR2(1000 BYTE) 
, ITEM_PROP NUMBER(2, 0) 
, ITEM_PRICE NUMBER(4, 0) 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
