--------------------------------------------------------
--  DDL for Table CHARACTER
--------------------------------------------------------

  CREATE TABLE "ONIGAWARA"."CHARACTER" 
   (	"USER_ID" VARCHAR2(100 BYTE), 
	"CHAR_NAME" VARCHAR2(100 BYTE), 
	"CHAR_LV" NUMBER(4,0), 
	"CHAR_STR" NUMBER(4,0), 
	"CHAR_DEX" NUMBER(4,0), 
	"CHAR_HP" NUMBER(4,0), 
	"CHAR_ATK" NUMBER(4,0), 
	"CHAR_DEF" NUMBER(4,0), 
	"CHAR_AGI" NUMBER(4,0), 
	"CHAR_CRT" NUMBER(4,0), 
	"CHAR_EXP" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEV
--------------------------------------------------------

  CREATE TABLE "ONIGAWARA"."DEV" 
   (	"DEV_ID" VARCHAR2(100 BYTE), 
	"DEV_PW" VARCHAR2(100 BYTE), 
	"DEV_EMAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EQUIP
--------------------------------------------------------

  CREATE TABLE "ONIGAWARA"."EQUIP" 
   (	"ITEM_CODE" NUMBER(4,0), 
	"CHAR_NAME" VARCHAR2(100 BYTE), 
	"USER_ID" VARCHAR2(100 BYTE), 
	"IDX" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVENTORY
--------------------------------------------------------

  CREATE TABLE "ONIGAWARA"."INVENTORY" 
   (	"CHAR_NAME" VARCHAR2(100 BYTE), 
	"ITEM_CODE" NUMBER(4,0), 
	"USER_ID" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ITEM
--------------------------------------------------------

  CREATE TABLE "ONIGAWARA"."ITEM" 
   (	"ITEM_CODE" NUMBER(4,0), 
	"ITEM_NAME" VARCHAR2(100 BYTE), 
	"ITEM_ATK" NUMBER(4,0), 
	"ITEM_DEF" NUMBER(4,0), 
	"ITEM_SUB" VARCHAR2(1000 BYTE), 
	"ITEM_PROP" NUMBER(2,0), 
	"ITEM_PRICE" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "ONIGAWARA"."MEMBER" 
   (	"USER_ID" VARCHAR2(100 BYTE), 
	"USER_PW" VARCHAR2(100 BYTE), 
	"NDATE" DATE, 
	"USER_EMAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MOB
--------------------------------------------------------

  CREATE TABLE "ONIGAWARA"."MOB" 
   (	"MOB_CODE" NUMBER(4,0), 
	"MOB_NAME" VARCHAR2(100 BYTE), 
	"MOB_LV" NUMBER(4,0), 
	"MOB_STR" NUMBER(4,0), 
	"MOB_DEX" NUMBER(4,0), 
	"MOB_PROP" NUMBER(2,0), 
	"MOB_SK1" NUMBER(4,0), 
	"MOB_SK2" NUMBER(4,0), 
	"MOB_SK3" NUMBER(4,0), 
	"MOB_SK4" NUMBER(4,0), 
	"MOB_SK5" NUMBER(4,0), 
	"MOB_SUB" VARCHAR2(1000 BYTE), 
	"MOB_ATK" NUMBER(4,0), 
	"MOB_DEF" NUMBER(4,0), 
	"MOB_HP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "ONIGAWARA"."NOTICE" 
   (	"NUM" NUMBER(8,0), 
	"USER_ID" VARCHAR2(100 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"REGDATE" DATE, 
	"MODDATE" DATE, 
	"READ_CNT" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTICE_CONTENT
--------------------------------------------------------

  CREATE TABLE "ONIGAWARA"."NOTICE_CONTENT" 
   (	"NUM" NUMBER(8,0), 
	"CONT" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SKILL
--------------------------------------------------------

  CREATE TABLE "ONIGAWARA"."SKILL" 
   (	"SK_CODE" NUMBER(4,0), 
	"SK_NAME" VARCHAR2(100 BYTE), 
	"SK_ATK" NUMBER(4,0), 
	"SK_DEF" NUMBER(4,0), 
	"SK_SUB" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
